services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile # Dockerfile location in backend foldere
    container_name: django_backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ../django/frontend:/frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BROWSER=none
